# Generated by Django 5.0.2 on 2024-03-18 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.election'),
        ),
        migrations.AddField(
            model_name='position',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.election'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration_app.position'),
        ),
        migrations.AddField(
            model_name='runningmate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.election'),
        ),
        migrations.AddField(
            model_name='runningmate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.position'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='running_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.runningmate'),
        ),
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.election'),
        ),
        migrations.AddField(
            model_name='voter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
