# Generated by Django 5.0.2 on 2024-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningmate',
            name='photo',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
