# Generated by Django 5.0.2 on 2024-03-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0003_alter_runningmate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration_app.position'),
        ),
    ]
